Awesome book using Class
Kandy-Peter/Awesome-Book pull request #2
Opened 2022-01-05 18:42 UTC by Kandy-Peter

This pull request contains the following steps and elements

-create a new js file
- Use class instead of a function to get and display data, create and remove books
- Add some styles to the template.
- fix bugs and Linters errors

2022-01-05 18:57 UTC, leolpaz requested changes
Hi @Kandy-Peter , 

You've done an amazing job so far, I'd like to highlight the following:
- Great job with the add book method
- Linter is passing

Some issues need to be resolved before your approval, but you're almost there!

<img src="https://media2.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>


## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-05 18:57 UTC, leolpaz commented on index.js
> +let bookArray = [];
- [ ] As pointed in the requirement screenshotted below, arrays should be inside the class, kindly refactor the code to do that
![image](https://user-images.githubusercontent.com/73140461/148272163-fe941b48-2f9a-44b9-8915-1f3d8b5bea29.png)

2022-01-05 18:57 UTC, leolpaz commented on index.js
> +    localStorage.setItem('bookstore', JSON.stringify(bookArray));
- [ ] As pointed in the requirement below, kindly refactor your remove, to be a class method
![image](https://user-images.githubusercontent.com/73140461/148272426-1cd029e8-8a4b-4509-a493-9ec97786634c.png)

2022-01-06 09:44 UTC, ShoiraTa reviewed
### **STATUS: APPROVED  ✔️** 
------
Hi @Kandy-Peter ,  

Your project is complete! There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

<img src="https://www.serialminds.com/wp-content/uploads/2015/11/loser.gif" width="400" height="250" />

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-06 09:46 UTC, merged